  name: Deploy React to GitHub Pages
  on:
    push:
      branches:
        - "gh-pages" # change to the branch you wish to deploy from
  
  permissions:
    contents: read
    pages: write
    id-token: write
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: build/drafter # change to your build folder
      environment:
        name: github-pages
        url: ${{ steps.build-publish.outputs.page_url }}

          
